export const userData = {
  user: {
    name: "Alex Chen",
    username: "@alexlistens",
    avatar_url: "https://i.pravatar.cc/150?img=32",
    member_since: 2018,
  },
  listening_stats: {
    total_minutes_this_year: 47832,
    total_artists: 342,
    total_tracks: 2847,
    listening_streak_days: 23,
  },
  top_genres: [
    { name: "Indie Rock", percentage: 28, color: "#1DB954" },
    { name: "Electronic", percentage: 22, color: "#AF2896" },
    { name: "Hip Hop", percentage: 18, color: "#FF6B35" },
    { name: "Jazz", percentage: 15, color: "#509BF5" },
    { name: "Classical", percentage: 9, color: "#E8115B" },
    { name: "Other", percentage: 8, color: "#777777" },
  ],
  top_artists: [
    {
      name: "Radiohead",
      play_count: 312,
      spotify_url: "https://open.spotify.com/artist/4Z8W4fKeB5YxbusRsdQVPb",
      image: "https://i.scdn.co/image/ab6761610000e5eba03696716c9ee605006047fd",
    },
    {
      name: "Kendrick Lamar",
      play_count: 287,
      spotify_url: "https://open.spotify.com/artist/2YZyLoL8N0Wb9xBt1NhZWg",
      image: "https://i.scdn.co/image/ab6761610000e5eb437b9e2a82505b3d93ff1022",
    },
    {
      name: "Khruangbin",
      play_count: 245,
      spotify_url: "https://open.spotify.com/artist/2mVVjNmdjXZZDvhgQWiakk",
      image: "https://i.scdn.co/image/ab6761610000e5eb5a6de3e9caboraf36ff0e80b6",
    },
    {
      name: "Floating Points",
      play_count: 198,
      spotify_url: "https://open.spotify.com/artist/2AR42Ur9PcchQDtEdwkv4L",
      image: "https://i.scdn.co/image/ab6761610000e5eb8c0debc44bra9f7df1bc0c11",
    },
    {
      name: "Nils Frahm",
      play_count: 176,
      spotify_url: "https://open.spotify.com/artist/5gqhueRUjMOHs4yDKyRiKQ",
      image: "https://i.scdn.co/image/ab6761610000e5eb55d29a0d42bra5c1bef5cc2e",
    },
  ],
  top_tracks: [
    {
      title: "Everything In Its Right Place",
      artist: "Radiohead",
      album: "Kid A",
      spotify_url: "https://open.spotify.com/track/2kJwzbxV2ppbEHCpMSACbm",
      duration: "4:11",
    },
    {
      title: "Not Like Us",
      artist: "Kendrick Lamar",
      album: "GNX",
      spotify_url: "https://open.spotify.com/track/6AI3ezQ4o3HUoP6Dhudph3",
      duration: "4:34",
    },
    {
      title: "Time (You and I)",
      artist: "Khruangbin",
      album: "Con Todo El Mundo",
      spotify_url: "https://open.spotify.com/track/7gSQxwCpEMjfnhceAido0y",
      duration: "4:01",
    },
    {
      title: "Nuits Sonores",
      artist: "Floating Points",
      album: "Elaenia",
      spotify_url: "https://open.spotify.com/track/1JVUvJGhhJYBlZqjVlRaLj",
      duration: "7:42",
    },
    {
      title: "Says",
      artist: "Nils Frahm",
      album: "Spaces",
      spotify_url: "https://open.spotify.com/track/47gKLvBp5gFslPOWEaiPRl",
      duration: "8:08",
    },
    {
      title: "Pyramid Song",
      artist: "Radiohead",
      album: "Amnesiac",
      spotify_url: "https://open.spotify.com/track/3CEKmGxQSTk3JlR3W08xhX",
      duration: "4:49",
    },
    {
      title: "Money Trees",
      artist: "Kendrick Lamar",
      album: "good kid, m.A.A.d city",
      spotify_url: "https://open.spotify.com/track/2HbKqm4o0w5wEeEFXm2sD4",
      duration: "6:26",
    },
    {
      title: "Cómo Me Quieres",
      artist: "Khruangbin",
      album: "Mordechai",
      spotify_url: "https://open.spotify.com/track/2bPGTMB5sFfFYQ2YvSmup0",
      duration: "3:33",
    },
  ],
  personality: {
    archetype: "The Sonic Explorer",
    tagline: "You don't follow trends — you find them first",
    traits: ["Eclectic", "Deep Listener", "Night Owl", "Album Purist"],
  },
  listening_clock: {
    morning: 15,
    afternoon: 20,
    evening: 35,
    night: 30,
  },
};
